CREATE DATABASE Accounting
GO
USE Accounting
GO

CREATE TABLE Countries (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(10) NOT NULL
);

CREATE TABLE Addresses (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  StreetName NVARCHAR(20) NOT NULL,
  StreetNumber INT,
  PostCode INT,
  City NVARCHAR(25) NOT NULL,
  CountryId INT NOT NULL,
  FOREIGN KEY (CountryId) REFERENCES Countries(Id)
);

CREATE TABLE Vendors (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(25) NOT NULL,
  NumberVAT NVARCHAR(15) NOT NULL,
  AddressId INT NOT NULL,
  FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);

CREATE TABLE Clients (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(25) NOT NULL,
  NumberVAT NVARCHAR(15) NOT NULL,
  AddressId INT NOT NULL,
  FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);

CREATE TABLE Categories (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(10) NOT NULL
);

CREATE TABLE Products (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(35) NOT NULL,
  Price DECIMAL(18,2) NOT NULL,
  CategoryId INT NOT NULL,
  VendorId INT NOT NULL,
  FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
  FOREIGN KEY (VendorId) REFERENCES Vendors(Id)
);

CREATE TABLE Invoices (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Number INT NOT NULL UNIQUE,
  IssueDate DATETIME2 NOT NULL,
  DueDate DATETIME2 NOT NULL,
  Amount DECIMAL(18,2) NOT NULL,
  Currency NVARCHAR(5) NOT NULL,
  ClientId INT NOT NULL,
  FOREIGN KEY (ClientId) REFERENCES Clients(Id)
);

CREATE TABLE ProductsClients (
  ProductId INT NOT NULL,
  ClientId INT NOT NULL,
  PRIMARY KEY (ProductId, ClientId),
  FOREIGN KEY (ProductId) REFERENCES Products(Id),
  FOREIGN KEY (ClientId) REFERENCES Clients(Id)
);